CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	role VARCHAR(25) NOT NULL DEFAULT 'USER',
	username varchar(25) UNIQUE NOT NULL,
	email CITEXT UNIQUE NOT NULL,
	password_hash bytea NOT NULL
);